---

#TimeOutScript_Path: ../timeout1.sh
#LicenseScript_Path: ../license_push_cloud1_centralized.sh
Configuration_File_Path: ../config_centralized.txt
uas_script: /ats/bin/sipp -sn uas -i 10.54.81.11 -p 14055 -m 50  
uac_script: /ats/bin/sipp -sn uac -i 10.54.81.11 -p 14444 10.34.227.185 -s 9966896556 -m 50 -d 120m  -r 1 -rp 1000 
#RollOver_Path: ../oamrollover.sh
SyncStatus_Path: ../sync_status_centralized.sh
#SwitchoverTime_Path: ../test_system_switchover_centralized.sh
#SwitchbackTime_Path: ../test_system_switchback_centralized.sh
#PortSwitchover_Path: ../port_switchover.sh
#PortSwitchoverTime_Path: ../test_port_switchover.sh
#PortSwitchback_Path: ../port_switchback.sh
#ServerSwitchover_Path: ../switch.sh
#CallCheck_Path: ../call.txt
#pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpynW0JpU2PeI9CVaq9Pt7elpf0uV1SvYMcsg7SuabnJhmY1g8hz1Ga+c7eZvPT1kGffVFaUScUyd1ZqnF8vxnLu3aQMwvOPAtnuewI0SDuaFLhZDK0Gu2mGrhrXLLTLSKdgoJYUk6Ur426D5YvghWiVERzCrWC7OU0nhDGH0wxuIor2oSvOWom1CPh8vlOWq3yj7yjES6yCKywAO+pWO5KK00CVrFtN1n/NIq795zlmvLW4693MMHamMgQ1AMAmF5Cw/yyQU/lvK0ME8dGPS/hUON5aG17iWaV17HXQW3+rFVXAVItFcDiWQ+x9ZcleLSqYZ35TwXqdC1hdrb+vt7 satykumar@bats12
#public key of bats12

isbc_centralized_nodes:
    - name: ISBC_CENTRALIZED_A
      present_or_absent: present
      template: ISBC_CENTRALIZED_ANSIBLE_ACTIVE.yml
      flavor: ansible
      base_build: sbc-V08.01.00R001-connexip-os_07.01.01-R001_7_amd64.qcow2
     # upgraded_build: TARGET_BUILD
      upgraded_build: sbc-V08.02.00R000-connexip-os_07.02.00-R000_4_amd64.qcow2
      security_group: ansible
      mgt0ipaddress: 10.34.224.85
      role: ACTIVE

    - name: ISBC_CENTRALIZED_S
      present_or_absent: present
      template: ISBC_CENTRALIZED_ANSIBLE_STANDBY.yml
      flavor: ansible
      base_build: sbc-V08.01.00R001-connexip-os_07.01.01-R001_7_amd64.qcow2
     # upgraded_build: TARGET_BUILD
      upgraded_build: sbc-V08.02.00R000-connexip-os_07.02.00-R000_4_amd64.qcow2
      security_group: ansible
      mgt0ipaddress: 10.34.224.86
      role: STANDBY




