---
  - name: Moving the files from localhost to active node
    copy:
      src: /home/ansible/sync_status.sh
      dest: /home/satykumar/sync_status.sh
      mode: '0777'
      force: yes

  - name: Waiting for ISBC active and standby to make a cluster
    shell: /home/satykumar/sync_status.sh {{ mgt0IPAddress_STANDBY }}
    register: b
    failed_when: b.rc not in (0,126)
  - debug: var=b.stdout_lines
  - name: sleep for 30 seconds and continue with play
    wait_for:
       timeout: 30

  - name: Sync status after active and standby spawned successfully
    become: true
    shell:
      " /opt/sonus/sbx/scripts/swinfo.sh"
    delegate_to: standby-1
    register: a
  - debug: var=a.stdout_lines

