  - name: Moving the files from localhost to active node
    copy:
      src: /home/ansible/config.txt
      dest: /root/
      mode: '0777'
  - name: To run configuration in active node
    shell: cat /root/config.txt | /opt/sonus/sbx/tailf/bin/confd_cli -u admin --noninteractive --noaaa
    register: b
  - debug: var=b.stdout_lines
  - name: check call status after rebuilding active
    shell: echo "show status global callCountStatus"| /opt/sonus/sbx/tailf/bin/confd_cli -u admin --noninteractive --noaaa
    delegate_to: standby-1
    register: b
  - debug: var=b.stdout_lines

