---
  - include: inventory_tsbc.yml
    no_log: True
  - include: delegate_tsbc.yml
    no_log: True

  - name: Rebuilding 2nd Active TSBC instance
    ignore_errors: yes
    register: stack_create
    os_stack:
       name: "{{ item.name }}"
       tag: "{{ item.name }}"  
       state: "{{ item.present_or_absent }}"
       validate_certs: false
       template: "{{ item.template }}"
       parameters:
           flavor: "{{ item.flavor }}"
           image: "{{ item.TSBC_UPGRADED_BUILD1 }}"
           security_group: "{{ item.security_group }}"
           mgt0IPAddress: "{{ item.mgt0ipaddress }}"
    loop: "{{ tsbc_nodes }}"
    when: item.mgt0ipaddress == ( tsbc_active2_mgt0ipaddress )


  - name: 2nd  Active  instance Failed to rebuild
    fail:
      msg: " Stack ({{ stack_create.results[0].stack.stack_name }})status: FAILED "
    when: stack_create.results[1].stack.status != "COMPLETE"
    loop: "{{ tsbc_nodes }}"


  - name: Waiting  till the 2nd  rebuilded Active TSBC  instance pings
    ignore_errors: yes
    wait_for:
       host: "{{ item.mgt0ipaddress }}"
       port: 2024
       delay: 60
       timeout: 120
       state: started
       msg: '"{{ item.mgt0ipaddress }}" didnot ping'
    loop: "{{ tsbc_nodes }}"
    loop_control:
       label: "{{ item.mgt0ipaddress }}"

       
  - name: Checking the Management  IP of 2nd rebuilded TSBC  instance is pinging.
    ignore_errors: yes
    shell: ping -c2 {{ item.mgt0ipaddress }}
    register: ping 
    retries: 5
    until: ping.stdout.find("0% packet loss") != -1
    loop: "{{ tsbc_nodes }}"
    loop_control:
       label: "{{ item.mgt0ipaddress }}"
  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ ping.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"


  - name: TSBC  INSTANCES DIDNOT PING
    fail:
      msg: ({{ item }}) donot ping
    when: item.rc != 0
    loop: "{{ ping.results }}"

 
  - name: wait for 30 seconds
    wait_for:
      timeout: 30
  

  - name: Checking if any core file generated on 1st  rebuilded   TSBC instance .
    ignore_errors: yes
    shell:
      "ls -alrt | grep -w core|wc -l"
    args:
     chdir: /var/log/sonus/sbx/coredump/
    delegate_to: "{{item}}"

    loop: "{{groups['tsbc']}}"


    register: core
    failed_when: '"0" not in core.stdout'

  - debug:
      msg: "{{ item.item }} has {{ item.stdout }} core files"
    loop: "{{ core.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"


  - name: Failed as core dump  file exist in  2nd rebuilded active  TSBC instance . See msg for more explanation .
    fail:
      msg: core dump exists in {{ item }}
    when: item.stdout != '0'
    loop: "{{ core.results }}"


  - name: Waiting for application to come up for 2nd  active  rebuilded  TSBC instance.
    ignore_errors: yes
    shell:
       "/usr/bin/tail -n 10  /var/log/sonus/lca/lca.log"
    register: service
    until: service.stdout.find("SBC service is now running") != -1
    retries: 60
    delay: 5
    delegate_to: "{{item}}"
    loop: "{{groups['tsbc']}}"


  - name: checking sync status for 2nd rebuilded  active  TSBC instance.See msg.
    fail:
      msg: "SBC service is not running for {{ item }}"
    when: "'SBC service is now running' not  in item.stdout"
    loop: "{{ service.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"



  - name: Application didnot come up for 2nd rebuilded active  TSBC instance .See msg for the specific instance.
    shell: curl -kisu 'admin:admin' -X GET https://{{item.mgt0ipaddress}}/api/operational/system/syncStatus/ | grep status
    register: sync_status
    loop: "{{ tsbc_nodes }}"
  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ sync_status.results }}"

#  - wait_for:
#      timeout: 20
#
#  - set_fact:
#       tsbc_active1: "{{ sync_status.results[0].stdout }}"
#       tsbc_active2: "{{ sync_status.results[1].stdout }}"
#       tsbc_standby: "{{ sync_status.results[2].stdout }}"
#
#
#  - name: Active1 MSBC instance is not in sync after rebuild
#    fail:
#      msg: services are not in sync for {{ sync_status.results[0].item.name }}
#    when: "'syncCompleted' not   in (tsbc_active1)"
#    loop: "{{ tsbc_nodes }}"
#
#
#  - name: Active2 MSBC instance is not in sync after rebuild
#    fail:
#      msg: services are not in sync for {{ sync_status.results[1].item.name }}
#    when: "'unprotectedRunningStandby' not   in (tsbc_active2)"
#    loop: "{{ tsbc_nodes }}"
#
#
#  - name: Standby MSBC instance is not in sync after rebuild
#    fail:
#      msg: services are not in sync for {{ sync_status.results[2].item.name }}
#    when: "'syncCompleted' not   in (tsbc_standby)"
#    loop: "{{ tsbc_nodes }}"
#
#
#  - wait_for:
#       timeout: 20
#
#
#  - name: checking installed software version after 2nd  rebuilded active  TSBC instances.
#    ignore_errors: yes
#    shell:
#          "/opt/sonus/sbx/scripts/swinfo.sh"
#    delegate_to: "{{ item }}"
#    loop: "{{ groups['tsbc'] }}"
#    register: version
#  - debug:
#      msg: "{{ item.stdout_lines }}"
#    loop: "{{ version.results }}"
#    loop_control:
#       label: "{{ item.stdout_lines }}"
# 
