---
  - name: Rebuilding  active SSBC instance .
    ignore_errors: yes
    register: stack_create
    any_errors_fatal: true
    os_stack:
       name: "{{ item.name }}"
       tag: "{{ item.name }}"  
       state: "{{ item.present_or_absent }}"
       validate_certs: false
       template: "{{ item.template }}"
       parameters:
           flavor: "{{ item.flavor }}"
           image: "{{ item.SSBC_UPGRADED_BUILD }}"
           security_group: "{{ item.security_group }}"
           mgt0IPAddress: "{{ item.mgt0ipaddress }}"
           sbc_ceRole: "{{ item.role }}"
           
    loop: "{{ ssbc_nodes }}"
    when: item.role == 'ACTIVE'


  - name: Standby  instance Failed to rebuild.
    fail:
      msg: " Stack ({{ stack_create.results[0].stack.stack_name }})status: FAILED "
    when: stack_create.results[0].stack.status != "COMPLETE"
    loop: "{{ ssbc_nodes }}"

  - name: Waiting  till the rebuilded active SSBC instance pings
    ignore_errors: yes
    wait_for:
       host: "{{ item.mgt0ipaddress }}"
       port: 2024
       delay: 60
       timeout: 120
       state: started
       msg: '"{{ item.mgt0ipaddress }}" didnot ping'
    loop: "{{ ssbc_nodes }}"
    loop_control:
       label: "{{ item.mgt0ipaddress }}"

  
       
  - name: Checking the Management  IP of rebuilded  Standby SSBC  instance is pinging.
    ignore_errors: yes
    shell: ping -c2 {{ item.mgt0ipaddress }}
    register: ping
    loop: "{{ ssbc_nodes }}"
    loop_control:
       label: "{{ item.mgt0ipaddress }}"
  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ ping.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"


  - name: REBUILDED  SSBC  INSTANCES DIDNOT PING
    fail:
      msg: ({{ item }}) donot ping
    when: item.rc != 0
    loop: "{{ ping.results }}"


 

  - include: inventory_ssbc.yml
    no_log: True


  - name: Checking if any core file generated on  rebuilded  active SSBC instance .
    ignore_errors: yes
    shell:
      "ls -alrt | grep -w core|wc -l"
    args:
     chdir: /var/log/sonus/sbx/coredump/
    delegate_to: "{{ item }}"
    loop: "{{groups['ssbc']}}"
    register: core
    failed_when: '"0" not in core.stdout'

  - debug:
      msg: "{{ item.item }} has {{ item.stdout }} core files"
    loop: "{{ core.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"

  - name: Failed as core dump  file exist in  rebuilded  active SSBC instance . See msg for more explanation .
    fail:
      msg: core dump exists in {{ item }}
    when: item.rc != 0
    loop: "{{ core.results }}"



  - name: Waiting for application to come up for rebuilded active SSBC instance.
    ignore_errors: yes
    shell:
       "/usr/bin/tail -n 10  /var/log/sonus/lca/lca.log"
    register: service
    until: service.stdout.find("SBC service is now running") != -1
    retries: 60
    delay: 5
    delegate_to: "{{item}}"
    loop: "{{groups['ssbc']}}"



  - name: Application didnot come up for rebuilded active SSBC instance .See msg for the specific instance.
    fail:
      msg: "SBC service is not running for {{ item }}"
    when: "'SBC service is now running' not  in item.stdout"
    loop: "{{ service.results }}"
    loop_control:
       label: "{{ item.stdout_lines }}"

#  - wait_for:
#     timeout: 20
#
#
#
#  - name: checking sync status for rebuilded  active SSBC instance.See msg.
#    shell: curl -kisu 'admin:admin' -X GET https://{{item.mgt0ipaddress}}/api/operational/system/syncStatus/ | grep status
#    register: sync_status
#    loop: "{{ ssbc_nodes }}"
#  - debug:
#      msg: "{{ item.stdout_lines }}"
#    loop: "{{ sync_status.results }}"
#    loop_control:
#       label: "{{ item.stdout_lines }}"
#
#
#  - set_fact:
#       ssbc_active: "{{ sync_status.results[0].stdout }}"
#       ssbc_standby: "{{ sync_status.results[1].stdout }}"
#
#
#  - name: Rebuilded Active ssbc instance is not in sync.
#    fail:
#      msg: services are not in sync for {{ sync_status.results[0].item.name }}
#    when: "'unprotectedRunningStandby' not   in (ssbc_active)"
#    loop: "{{ ssbc_nodes }}"
#
#  - name: Standby ssbc instance is not in sync.
#    fail:
#      msg: services are not in sync for {{ sync_status.results[1].item.name }}
#    when: "'syncCompleted' not   in (ssbc_standby)"
#    loop: "{{ ssbc_nodes }}"
#
#
#
#  - name: checking installed software version for rebuilded  active SSBC instances.
#    ignore_errors: yes
#    shell:
#          "/opt/sonus/sbx/scripts/swinfo.sh"
#    delegate_to: "{{ item }}"
#    loop: "{{ groups['ssbc'] }}"
#    register: version
#  - debug:
#      msg: "{{ item.stdout_lines }}"
#    loop: "{{ version.results }}"
#    loop_control:
#       label: "{{ item.stdout_lines }}"
#
#
