---
  - name: To check box switchover time
  #  shell:
  #        " sh test_system_switchover.sh" {{ mgt0IPAddress_ACTIVE }} {{ mgt0IPAddress_STANDBY }}
  #  args:
  #    chdir: /home/ansible/
    shell: /home/ansible/test_system_switchover.sh {{ mgt0IPAddress_ACTIVE }} {{ mgt0IPAddress_STANDBY }} 
    register: b
  - debug: var=b.stdout_lines

