---
- name: Gather facts about a previously created image named image1
  os_image_facts:
    auth:
      auth_url: https://10.34.224.10:13292
      username: ribbon	
      password: ribbon1
      project_name: admin
    image: centos_qcow2

- name: Show openstack facts
  debug:
    var: openstack_image
