---
- name: Launch instance on OpenStack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy an instance
      os_server:
        state: present  	
        name: mukul
        image: centos_qcow2
        validate_certs: false
        key_name: ansiblemaster
        timeout: 200
        flavor: test
        network: PR_MGMT
        meta:
          hostname: mukul.localdomain
