---
- name: create stack
  hosts: localhost
  gather_facts: true
  ignore_errors: true
  tasks:
  - name: ISBC
    os_stack:
       name: ISBC_active
       tag: stack
       state: present
       validate_certs: false
       template: Test_active_ISBC_SRIOV_1.yaml
       parameters:
           flavor: ISBC4VCPU
           image: cSBC_V08.00.00R000
           security_group: SONUS
  - name: Waiting for Mgmt IP to comeup       
    wait_for: timeout=400
  - name: Checking the Mgmt IP is pingable or not
    shell: ping -c2 10.34.224.111
    register: p
  - debug: var=p.stdout_lines
  - name: To do SSH, login as a root,check the SBC service and node is running in active role
    shell: ssh -o  "stricthostkeychecking no" -p 2024 -i /home/ansible/cloud_ats.key root@10.34.224.111 "egrep 'SBC service is now running|Node is running in ' /var/log/sonus/lca/lca.log"
    register: q
  - debug: var=q.stdout_lines
  - name: To check installed software version
    shell: ssh -o  "stricthostkeychecking no" -p 2024 -i /home/ansible/cloud_ats.key root@10.34.224.111 "sh /opt/sonus/sbx/scripts/swinfo.sh"
    register: r
  - debug: var=r.stdout_lines
  - name: ISBC active is completed successfully , now spwanning ISBC standby mode
    os_stack:
       name: ISBC_standby
       tag: stack
       state: present
       validate_certs: false
       template: Test_standby_ISBC_SRIOV_1.yaml
       parameters:
           flavor: ISBC4VCPU
           image: cSBC_V08.00.00R000
           security_group: SONUS
  - name: Waiting for Mgmt IP to comeup
    wait_for: timeout=400
  - name: Checking the Mgmt IP is pingable or not
    shell: ping -c2 10.34.224.112
    register: s
  - debug: var=s.stdout_lines
  - name: To do SSH, login as a root,check the SBC service and node is running in standby role
    shell: ssh -o  "stricthostkeychecking no" -p 2024 -i /home/ansible/cloud_ats.key root@10.34.224.112 "egrep 'SBC service is now running|Node is running in ' /var/log/sonus/lca/lca.log"
    register: t
  - debug: var=t.stdout_lines
  - name: To check installed software version
    shell: ssh -o  "stricthostkeychecking no" -p 2024 -i /home/ansible/cloud_ats.key root@10.34.224.112 "sh /opt/sonus/sbx/scripts/swinfo.sh"
    register: u
  - debug: var=u.stdout_lines
  - name: Waiting for ISBC active and standby to make a cluster
    wait_for: timeout=60
  - name: ISBC active and standby mode is completed successfully , below are the software version installed on ISBC active and standby
    shell: ssh -o  "stricthostkeychecking no" -p 2024 -i /home/ansible/cloud_ats.key root@10.34.224.111 "sh /opt/sonus/sbx/scripts/swinfo.sh"
    register: n
  - debug: var=n.stdout_lines
  - name: to push license
    shell: sh /home/ansible/license_push_cloud.sh 
  - name: To copy the config file to active node
    shell: scp -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key -P 2024 /home/ansible/config.sh root@10.34.224.111:/root
  - name: To run configuration in active node
    shell: ssh -p 2024 -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key root@10.34.224.111 "expect /root/config.sh"
  - name: To copy the config file to standby node
    shell: scp -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key -P 2024 /home/ansible/config.sh root@10.34.224.112:/root
  - name: To run configuration in standby node
    shell: ssh -p 2024 -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key root@10.34.224.112 "expect /root/config.sh"
  - name: Running the call(uas)
    shell: ssh -p 22 -o  "stricthostkeychecking no" satykumar@10.54.81.66 "/ats/bin/sipp -sn uas -i 10.54.81.66 -p 14419 -bg "
  - name: Running the call(uac)
    shell: ssh -p 22 -o  "stricthostkeychecking no" satykumar@10.54.81.66 "/ats/bin/sipp -sn uac -i 10.54.81.66 -p 16829 10.34.226.111 -s 9966896446 -m 10 -d 2000 -bg"
  - name: To copy the callcount script in remote box
    shell: scp -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key -P 2024 /home/ansible/call.sh root@10.34.224.111:/root
  - name: Call Count
    shell: ssh -p 2024 -o  "stricthostkeychecking no" -i /home/ansible/cloud_ats.key root@10.34.224.111 "expect /root/call.sh"
    register: v
  - debug: var=v.stdout_lines

