- name: launch a compute instance
  ignore_errors: true
  gather_facts: true
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        state: present
        name: vm1
        validate_certs: false
        region_name: regionOne
        availability_zone: ansible
        image: b3dce9f8-4aa5-46a2-b3b6-0ed242a604f1
        key_name: ansiblekey
        timeout: 200
        flavor: 4daa1d1d-5d04-4a56-b794-7310ef6692b1
        security_groups: default
        auto_ip: yes
        network: 0af61f03-c3e0-4aa5-ad65-565337ef779b
        wait: no
